### PR TITLE
Update to Laurine version 0.2.1

### PR DESCRIPTION
**Pull request by Jeehut**
This updates the script to point to the current version 0.2.1.

### CODE REVIEW

**Comment by JiriTrecak** [comment]
Hey, thank you - while I'd like to push it, I am actually working on 0.3 version that contains a lot of changes and I will release it most probably over the weekend, so this might become redundant. 

Thank you again!
Sincerely,
JT

**Comment by Jeehut** [comment]
Well, it's two days until weekend and this is not going to hurt, so why not just merge?

**Comment by Jeehut** [comment]
Thanks! :+1:

**Comment by JiriTrecak** [comment]
Yes, you are right, I just needed to test it. :) Thanks man :)

**Comment by Jeehut** [comment]
You're welcome. Thanks for such a great library! :)

**Pull request merged**
